### ISSUE TITLE
HC crashed NEI

### ISSUE THREAD

**Issue by zortag** [K-4U/Hydraulicraft#116] opened 2015-01-10 12:50 UTC
Forge 10.13.2.1284
CodeChickenCore-1.7.10-1.0.4.29-universal
NotEnoughItems-1.7.10-1.0.4.83-universal
HydCraft-1.7.10-2.0.78-universal

i got this crash while whatching any recipe in nei.
http://pastebin.com/Y1eR8Zxy

**Comment by K-4U** [comment] 2015-01-10 12:51
Duplicate of #115. Although i really prefer your way of making the issue.
Has already been fixed. Was about to upload the file to curseforge!

**Closed by K-4U** 2015-01-10 12:51 UTC

**Comment by zortag** [comment] 2015-01-10 15:13
i found it happen with BluePower-1.7.10-0.2.835-universal installed.
all works with BluePower-1.7.10-0.2.811-universal
