### ISSUE TITLE
WorldGenOil crash with SpongeForge

### ISSUE THREAD

**Issue by ajthemacboy** [K-4U/Hydraulicraft#202] opened 2016-02-16 15:21 UTC
Crash report: https://gist.github.com/ajthemacboy/65145602dc6175478da4

This crash only occurs with SpongeForge installed. This occurs on Forge 1732 with the latest version of SpongeForge installed.

**Comment by K-4U** [comment] 2016-02-16 15:26
Duplicate of #188

**Closed as completed** 2016-02-16 15:26 UTC

**Comment by ajthemacboy** [comment] 2016-02-16 17:49
Are you certain this is a duplicate?

This crash ONLY occurs with the SpongeForge mod installed, and the crash directly mentions Sponge.
